language: elixir
sudo: false
matrix:
  include:
    - elixir: 1.6
      otp_release: 20.0
      env: MIX_ENV=test
    - elixir: 1.7
      otp_release: 20.0
      env: MIX_ENV=test UUID=resource_owners
    - elixir: 1.7
      otp_release: 20.0
      env: MIX_ENV=test UUID=all
script:
  - mix deps.compile
  - mix test
after_script:
  - mix credo
